### ISSUE TITLE
Implementing task1.3

### ISSUE THREAD

**Issue by m4n1c22** [m4n1c22/OS2_Lab#1]
Integrating the feature of having error probability of 0.5 or 50% in the program defined for parent-child relationship.
- Create a clone version of the [task1.c](https://github.com/m4n1c22/OS2_Lab/blob/master/Lab1/code/task1/task1.c) file.
- Modify the cloned file with necessary changes as described by the task1.3
- For testing the code. Kindly make modification in the Makefile to suit the same. 
- It would be better if there exist a new target to compile the source code for task1.3 and another target for executing it inside the existing [Makefile](https://github.com/m4n1c22/OS2_Lab/blob/master/Lab1/code/task1/Makefile).  
- Utilize the variable child_exit_status defined in the [task1.c](https://github.com/m4n1c22/OS2_Lab/blob/master/Lab1/code/task1/task1.c) file. You can verify the value of the child_exit_status with all the standard wait call errors and execution errors raised by the child process on the parent process.
- Create a new target named error_prog a clone of prog target inside Makefile. It will compile $(TASK_1_3_SRC) instead of $(TASK_1_SRC). You can define a new storage specifier named $(TASK_1_3_SRC) inside Makefile and assign with your task1_3 src file name.
- Similarly Create another target named error_exec a clone of exec target inside Makefile. It will have dependency on error_prog target and execute ./error_prog executable instead of ./prog.
- Create a cloned shell script task1_3_scr.sh with the same content from task1_1.sh. Invoke make error_exec instead of make exec in the script. Also write it to the log file error_overall.log instead of overall.log
- The created shell script is invoked via Makefile target. Therefore, create a target named test_error cloned target of test but will have dependency as error_prog instead of prog and execute task1_3_scr.sh instead of task1_1.sh. You can create a storage specifier named $(TASK1_3_SCR) = task1_3_scr.sh and use the same inside the Makefile.

**Comment by Kanvas89** [comment]
I have started working on it and will be completed this task by Thursday
05/05/2016 afternoon.

On Tue, May 3, 2016 at 10:33 PM, Sreeram Sadasivam <notifications@github.com

> wrote:
> 
> Integrating the feature of having error probability of 0.5 or 50% in the
> program defined for parent-child relationship.
> - Create a clone version of the task1.c
>   https://github.com/m4n1c22/OS2_Lab/blob/master/Lab1/code/task1/task1.c
>   file.
> - Modify the cloned file with necessary changes as described by the
>   task1.3
> - For testing the code. Kindly make modification in the Makefile to
>   suit the same.
> - It would be better if there exist a new target to compile the source
>   code for task1.3 and another target for executing it inside the existing
>   Makefile
>   https://github.com/m4n1c22/OS2_Lab/blob/master/Lab1/code/task1/Makefile
>   .
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/m4n1c22/OS2_Lab/issues/1

## 

Warm Regards,
Anand K Vashishtha

**Comment by m4n1c22** [comment]
Task completed. Testing pending.
