### ISSUE TITLE
Parent process failure with child process assuming the parent role

### ISSUE THREAD

**Issue by m4n1c22** [m4n1c22/OS2_Lab#7]
Given the issues [1](https://github.com/m4n1c22/OS2_Lab/issues/5) and [2](https://github.com/m4n1c22/OS2_Lab/issues/6) are meant to detect the parent process failures. There is no step taken to revive the child process to acquire the role of the parent. Implement such a functionality by child process acquiring the role of parent when parent process crashes. For testing purposes make the parent process not to wait for its child. Refer task3.1 in the [document](https://github.com/m4n1c22/OS2_Lab/blob/master/Lab1/doc/lab1-process-pairs.pdf)

**Comment by ggulesir** [comment]
This should be done for which task? I already did this functionality for task3? Sreeram you are confusing me!

**Comment by m4n1c22** [comment]
I am sorry for the confusion. I just assigned it you since you were doing
it.

Regards,
*Sreeram Sadasivam*
*Fachbereich Informatik | Technische Universität Darmstadt*
Ph: +49-17680826365
email id: sreeram.sadasivam@gmail.com

**Comment by m4n1c22** [comment]
@ggulesir  I am sorry for the confusion. I just assigned it to you since you were doing it.

**Comment by ggulesir** [comment]
Kein problem :D just wanted to be sure what is left.
