### ISSUE TITLE
Testing & Debugging Task2.1 & Task 2.2

### ISSUE THREAD

**Issue by m4n1c22** [m4n1c22/OS2_Lab#9]
Execute and test task 2.1 and task 2.2
**Testing Task 2.1:**
- Run `make clean` first.
- Execute `make comp_server_task_2_1` for compiling the task 2.1
- Run `make server_exec_task_2_1` for running the task 2.1. You can also run the executable `server_task_2_1.bin` from terminal after compilation as: `./server_task_2_1.bin -n 10`. `-n` is the option for specifying the maximum number of forks created. You can also avoid specifying this option which will create by default 5 child processes. _Note: value of n ranges from 1-50_

**Testing Task 2.2:**
- Open two terminal windows.
- Run `make clean` first.
- Execute `make comp_server_task_2_2` for compiling the server code for task 2.2 in the first terminal window.
- Execute `make comp_client_task_2_2` for compiling the client code for task 2.2 in the second terminal window.
- Run `make server_exec_task_2_2` for running the task 2.2 server program. You can also run the executable `server_task_2_2.bin` from terminal after compilation as: `./server_task_2_2.bin -n 10`. `-n` is the option for specifying the maximum number of forks created. You can also avoid specifying this option which will create by default 5 child processes. _Note: value of n ranges from 1-50. And the fact that execution of the server code should be done from the first terminal window._ 
- You will notice server program waits for requests. Therefore, in the second terminal window execute `make client_exec_task_2_2`.
- The requests would be created by clients and stored in a folder named **_request_**. Server process will process the requests from the above mentioned folder and delete them as soon as it is processed.

Kindly test all the edge case and random case testing involved with the above execution style. If possible write a shell script which can automate them.

**Comment by ggulesir** [comment]
![screenshot at 2016-05-11 17 08 35](https://cloud.githubusercontent.com/assets/8045250/15185886/2cf5db30-179b-11e6-89b6-3e7830eb794a.png)
![screenshot at 2016-05-11 17 08 59](https://cloud.githubusercontent.com/assets/8045250/15185892/31b5b71c-179b-11e6-8aaa-eb6036930051.png)

For task 2.1 it looks like when 1000 given as a number of fork requests, it creates 1000 instead of stopping at 50 which is the limit as I understood from the assignment sheet.

**Comment by m4n1c22** [comment]
@ggulesir Thanks for pointing out the bug. I have resolved it now. You can pull the code and test it again.

**Comment by ggulesir** [comment]
Tested manually, both 2.1 and 2.2 worked as expected.
